# Generated by Django 4.2.7 on 2025-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('trabajador', 'Trabajador'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='defaultuser', max_length=150, unique=True),
        ),
    ]
