# Generated by Django 5.2.6 on 2025-09-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('trabajador', 'Trabajador'), ('admin', 'Administrador'), ('superadmin', 'Superadministrador')], default='cliente', max_length=20),
        ),
    ]
