# Generated by Django 5.2.3 on 2025-09-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_discount_percent_product_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Pisos', 'pisos'), ('Cocinas', 'cocinas'), ('Construcción', 'construcción'), ('Maderas y Puertas', 'maderas y puertas'), ('Limpieza', 'limpieza'), ('Ferretería y Cerrajería', 'ferretería y cerrajería'), ('Electrodomésticos', 'electrodomésticos'), ('Exteriores', 'exteriores'), ('Muebles y Organización', 'muebles y organización'), ('Pinturas', 'pinturas'), ('Baños', 'baños'), ('Plomería', 'plomería'), ('Seguridad', 'seguridad'), ('Lámparas', 'lámparas'), ('Herramientas', 'herramientas'), ('Electricidad', 'electricidad'), ('Decoración', 'decoración'), ('Automotriz', 'automotriz')], max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
