# Generated by Django 5.2.3 on 2025-09-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_image_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rif',
        ),
    ]
