# Generated by Django 5.2.6 on 2025-09-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_rif'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the product', verbose_name='Description'),
        ),
    ]
