# Generated by Django 5.2.5 on 2025-09-01 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(help_text='The associated user account for this person.', on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(help_text='The personal information of the employee.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_record', to='human_resources.person', verbose_name='Person'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('is_venezuelan', 'identity_number')},
        ),
    ]
