# Generated by Django 5.2.5 on 2025-09-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fiscal_address',
            field=models.CharField(blank=True, help_text='Fiscal address of the organization.', max_length=100, null=True, verbose_name='Fiscal Address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='rif',
            field=models.CharField(default='', help_text='Tax identification number of the organization.', max_length=10, verbose_name='RIF'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the location.', max_length=255, verbose_name='Location Name')),
                ('address', models.CharField(help_text='Physical address of the location.', max_length=100, verbose_name='Address')),
                ('state', models.CharField(help_text='State of operation.', max_length=255, verbose_name='State')),
                ('organization', models.ForeignKey(help_text='The organization this location belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='human_resources.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='PersonInfoContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_province', models.CharField(help_text='State or province of residence.', max_length=255, verbose_name='State/Province')),
                ('municipality', models.CharField(help_text='Municipality of residence.', max_length=255, verbose_name='Municipality')),
                ('parish', models.CharField(help_text='Parish of residence.', max_length=255, verbose_name='Parish')),
                ('postal_code', models.CharField(help_text='Postal code of the area.', max_length=10, verbose_name='Postal Code')),
                ('personal_address', models.CharField(help_text='Detailed personal address.', max_length=100, verbose_name='Personal Address')),
                ('local_phone_prefix', models.CharField(blank=True, help_text='Prefix for local phone number.', max_length=4, null=True, verbose_name='Local Phone Prefix')),
                ('local_phone_number', models.CharField(blank=True, help_text='Local phone number.', max_length=7, null=True, verbose_name='Local Phone Number')),
                ('mobile_phone_prefix', models.CharField(help_text='Prefix for mobile phone number.', max_length=4, verbose_name='Mobile Phone Prefix')),
                ('mobile_phone_number', models.CharField(help_text='Mobile phone number.', max_length=7, verbose_name='Mobile Phone Number')),
                ('person', models.OneToOneField(help_text='Related person for this contact information.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='human_resources.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Person Contact Info',
                'verbose_name_plural': 'Person Contact Info',
            },
        ),
    ]
