# Generated by Django 5.2.5 on 2025-09-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_organization_fiscal_address_organization_rif_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
