# Generated by Django 5.2.6 on 2025-09-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_leavetype_schedule_leaverequest_employeeschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfocontact',
            name='local_phone_number',
            field=models.CharField(blank=True, help_text='Local phone number.', max_length=10, null=True, verbose_name='Local Phone Number'),
        ),
        migrations.AlterField(
            model_name='personinfocontact',
            name='mobile_phone_number',
            field=models.CharField(help_text='Mobile phone number.', max_length=10, verbose_name='Mobile Phone Number'),
        ),
    ]
