# Generated by Django 4.2.7 on 2025-09-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='client_type',
            field=models.CharField(choices=[('construction_company', 'Construction Company'), ('hardware_store', 'Hardware Store'), ('general_public', 'General Public'), ('other', 'Other')], default='construction_company', help_text="The type of client, e.g., 'Construction Company'.", max_length=50, verbose_name='Client Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, help_text='The name of the main contact person for the customer.', max_length=255, null=True, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_purchase',
            field=models.DateTimeField(blank=True, help_text="The date and time of the customer's last purchase.", null=True, verbose_name='Last Purchase'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('delinquent', 'Delinquent'), ('new', 'New')], default='active', help_text='The current status of the customer.', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, help_text='The tax identification number (e.g., RUC) of the customer.', max_length=50, null=True, unique=True, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text='The physical address of the customer.', null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='The main email address of the customer.', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='The full name or business name of the customer.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='The primary phone number of the customer.', max_length=20, null=True, verbose_name='Phone'),
        ),
    ]
