# Generated by Django 4.2.7 on 2025-09-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_client_type_customer_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='lead',
            name='plazo_pago',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='certificado',
            field=models.BooleanField(default=False, help_text='Proveedor certificado', verbose_name='Certificado'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Contacto'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('inactivo', 'Inactivo')], default='activo', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='plazo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('15_dias', '15 días'), ('30_dias', '30 días'), ('60_dias', '60 días'), ('90_dias', '90 días')], default='30_dias', max_length=50, verbose_name='Plazo de Pago'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='razon_social',
            field=models.CharField(default='', max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rubro',
            field=models.CharField(choices=[('construccion', 'Construcción'), ('ferreteria', 'Ferretería'), ('materiales', 'Materiales'), ('otros', 'Otros')], default='construccion', max_length=50, verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ruc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
