# Generated by Django 4.2.7 on 2025-09-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_supplier_address_remove_supplier_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='plazo_pago',
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source'),
        ),
    ]
